site_name: bakery
site_description: It's all about a Bakery
repo_url: https://github.com/ankitksr/bakery-management
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/ankitksr">ankitksr</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
